<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="chendaqian" name="testdemo" tests="2" failures="1" timestamp="19 Aug 2017 08:30:40 GMT" time="0.072" errors="0">
  <testcase name="test01" time="0.004" classname="Car.CarTest">
    <failure type="java.lang.AssertionError" message="expected [3] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [4]
	at Car.CarTest.test01(CarTest.java:18)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- test01 -->
  <testcase name="test02" time="0.0" classname="Car.CarTest"/>
</testsuite> <!-- testdemo -->
